### ISSUE TITLE
Pointer Write and Read 1D Array methods should check the provided buffer has enough elements allocated.

### ISSUE THREAD

**Issue by ryanpoulos** [ryanpoulos/LabVIEW-Memory#3]
Currently, the Pointer class' Read and Write methods for 1D arrays only checks the Pointer to make sure it has a large enough size for the transfer. This is good, but LabVIEW can still crash if the provided buffer array doesn't have enough (**count**) elements. So it should check both conditions (Pointer size and array size).

**Comment by mattlutomski** [comment]
Good catch; I'll get it fixed this afternoon.

**Comment by mattlutomski** [comment]
Merged modified code that fixes this issue from branch #4 back into develop.
