### ISSUE TITLE
LabVIEW crashes when I call Dispose twice.

### ISSUE THREAD

**Issue by csjall** [ryanpoulos/LabVIEW-Memory#7]
Currently there is nothing that prevents me from double disposing a memory block. We should add a pointer check to the (safe) API before disposing memory.

**Comment by ryanpoulos** [comment]
I added the check, but oddly enough if you call Dispose twice in succession, they both say the pointer is valid. I would think the second check would fail, but for some reason it doesn't. Either way, it no longer crashes LabVIEW and will still catch situations where a user tries to deallocate a pointer not allocated by LabVIEW.
